### ISSUE TITLE
Ever used in production ?

### ISSUE THREAD

**Issue by amallo** [eduardomoroni/react-clean-architecture#1]
Hi @eduardomoroni, very interesting, did you ever used this approach on a true project ?

**Comment by eduardomoroni** [comment]
Kindof, we use a similar approach on a React/Mobx application. Our production implementation was a bit different because we're inside a [micro frontend architecture](https://micro-frontends.org/). Honestly, this repository is more a POC than a production-ready implementation.
I'm struggling to find time to write an article explaining why I came into this solution and why I think it's a good approach.

If you have a strong business motivation to share logic AND you got the point of this repository I'd say go for it. 
But I think this is way easier when you're using Mobx because you can have stores with shared logic and application specific stores.
The reason why I wrote in Redux? Because redux is easier to have people seeing and giving feedbacks. BTW feedbacks are welcome 👍🏽

**Comment by amallo** [comment]
Thanks for your reply, will be very interested by your (future) article ! I am looking for best practises for  separation of concern  and scaling react native app, specially I would like to 

- separate my business logic from UI and make it easily testable,
- share logic between native and web

I will give a look at Mobx !

**Comment by eduardomoroni** [comment]
I believe that, Clean architecture is a good start. It's Far away from
being a silver bullet but it's a good way pretty good start point.
Another suggestion is follow smart/Dumb components.
The main pain point you have to be prepared is the increase of mapping
objects boilerplate.
You'll have to map from data to domain layer. From domain to presentation
later. From smart to dumb components. And all testa associated with this.
Having flowtype can minimize how much you have to test. Take a look at
repository referência, it'll be clarifying. 👍

Em sex, 10 de ago de 2018 9:44 AM, amallogia <notifications@github.com>
escreveu:
