### ISSUE TITLE
Project is build with errors

### ISSUE THREAD

**Issue by ModPhoenix** [eduardomoroni/react-clean-architecture#2]
Regards!
When I executing a command `yarn start` getting an error:

```
Failed to compile.

C:/Projects/react-clean-architecture/authentication/web/node_modules/core/dist/adapters/redux/saga.d.ts
(16,54): Cannot find module '../../../../../../../Projects/react-clean-architecture/authentication/core/node_modules/redux-saga/effects'.
```

And I needed to change the import path: `"core": "file:../core"` to `"core": "../core"`

System:

Windows 10
Node: 10.15.3
Yarn: 1.15.2

**Comment by eduardomoroni** [comment]
Thanks @ModPhoenix, I'll fix this here.

**Comment by ModPhoenix** [comment]
I tried but could not start the project.
Just wanted to let know that there is such a problem on Windows.

**Comment by eduardomoroni** [comment]
Thanks for letting me know.
Seems like the symlink proccess works different on windows environment.
![image](https://user-images.githubusercontent.com/823150/56880096-b4d5f600-6a5b-11e9-91de-51e2870d67ea.png)

I'll push a fix soon.

**Comment by eduardomoroni** [comment]
@ModPhoenix could you try once more?

The fix:
- delete you `authentication/node_modules`
- go to `core/`, then run `npm install` and `npm run build`
- go back to authentication module, and now run `npm install` and `npm start`.

Explaining the problem:
The installation process relies on symlinking, the normal process would be:
- Once you run `npm install` on the authentication module, npm hook will also install `core` module.
- Once you run `npm start` on the authentication module, npm hook will build the `core` module and then start the app.

The problem is that this `npm run build` on the `core` module is not being reflected on `authentication/node_modules/core` because during the installation npm is not properly symlinking.

I really appreciate your issue. Thanks

**Comment by ModPhoenix** [comment]
Thanks @eduardomoroni, now everything works)
