### ISSUE TITLE
Core npm package doesn't hot refresh upon update in the react native project

### ISSUE THREAD

**Issue by SaundersB** [eduardomoroni/react-clean-architecture#49]
When running the project a pretty big downside is the core module won't push an update to hot refresh when running the app during development. This is a pretty significant downside during development. Perhaps the web and native modules might suffer the same problem when loaded in the package.json file as: `"file:../<module_name>"` as a dependency.

**Comment by eduardomoroni** [comment]
You're correct, but this also depends on your setup. You could configure your bundler to watch for changes on any external folder (same for metro bundler on RN side).
This repository is just an idea on how we could implements clean architecture on react codebases.
In the pure theoretical word, which I know I far from reality, you should not have your business rules depending on the UI. So it is actually not needed to have a hot refresh, because you have to develop your business rules completely uncoupled from the UI. And then your UI will consume the business logic.
But I know that in the real world is not like that. 
It also worth taking a look at Lerna packages, that could also help on better tooling around this architecture.
With my 11/02/2020 mind, I would definitely use Expo web to do all this crazy stuff.

Thanks for your issue. I will keep it open to let people know this downside.

**Comment by SaundersB** [comment]
I have one other question. I wasn't sure the best way to ask but I figured I'd put it here.

How do the following map between the README and core/lib folder?

* **Entity:** <-> core/lib/entities
* **Interactor:** <-> core/lib/useCases
* **Adapter:** <-> core/lib/adapters, core/lib/services, core/lib/frameworks
* **Presenter:** <-> core/lib/useCases
* **Components:** web/src/components, native/src/components

Does this look right?

**Comment by eduardomoroni** [comment]
That's an interesting question, that made me think about the current implementation.
But the thing is that the clean architecture, per say, it's all about having well defined (and pure) entities and making sure that the use cases define the interactions (probably that's why lots of implementations also calls them as interactors). So yes these assumptions are correct:
- Entity: <-> core/lib/entities
- Interactor: <-> core/lib/useCases
- Adapter: <-> core/lib/adapters (In this case is how to adapt our use cases to Redux)
- Components: web/src/components, native/src/components

The presenter though, has ended up being the react-redux, a layer to connect the adapter to the UI elements.
I think that conceptually would be better to having the old fashion idea of "Presentational and Container", in which the presenters are actually the Container components that will later branch out to web or mobile components. But this approach IMHO doesn't help much and adds lots of complexity on the abstraction, it's quite hard to keep this container component cross-platform.

The services folder is the external services we're going to connect, sometimes it's platform specific some other time it's a shared API. That's why we have on the core directory.
Frameworks folder was just bad naming, it's the framework initialization.

Let me know if I was able to explain, feel free to ask further questions.

**Comment by eduardomoroni** [comment]
closing the issue, but feel free to ask further questions or reach me out on https://keybase.io/eduardomoroni/chat
