### ISSUE TITLE
Question about counter

### ISSUE THREAD

**Issue by gabriel-lima96** [eduardomoroni/react-clean-architecture#72]
First of all, thank you for the great article. It really helped me to understand a little better how to think of a clean architecture for future projects.

In [this file](https://github.com/eduardomoroni/react-clean-architecture/blob/master/counter/core/lib/useCases/CounterInteractor.ts) is it right for the `increment` and `decrement` function to return the counter entity? Doesn't it break the encapsulation/constraint that the useCase is supposed to maintain (application logic)?
e.g: `counterInteractior.decrement(1).decrement(20)`

Also, in the same file, `this.counter = new Counter(this.higherBound)` ins't it bad, not only for the performance but also for not keeping the object state (if it had more states besides the count)?

**Comment by eduardomoroni** [comment]
> In this file is it right for the increment and decrement function to return the counter entity? Doesn't it break the encapsulation/constraint that the useCase is supposed to maintain (application logic)?
e.g: counterInteractior.decrement(1).decrement(20)

You're absolutely right, this is a flaw that will lead to consumers to "bypass" the business rule. and that is one of the issues you may want to avoid.
That's a good catch, I will try to fix this issue (also feel free to submit a PR).

> Also, in the same file, this.counter = new Counter(this.higherBound) ins't it bad, not only for the performance but also for not keeping the object state (if it had more states besides the count)?
Yep, I don't remember why I've done like that. I'd say that was mostly for convenience. When applying clean architecture to a real app it's important to strike a balance between purism and convenience. A 100% pure implementation would make uncle bob happy but it would easy turn into a pain in the neck. A 100% convenient implementation would defeat the purpose of following the architecture.
A quick side-note on the performance topic: micro-performance tuning (like using `new Foo()` instead of `foo = {}`) will most of the time be waste of developers and teams time. Unless you're working on a system that fraction of second make an actual difference. 
I don't use class constructors most of the time, mostly due to the fact that will lead to a non-idiomatic codebase. The reason I am using class, is to make easier for folks with other object-oriented languages to understand.
